apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-node
  labels: 
    service-name: hello-node
spec:
  replicas: 3
  selector:
    matchLabels:
      service-name: hello-node
  template:
    metadata:
      name: hello-node
      labels:
        service-name: hello-node
    spec:
      containers:
      - name: hello-node
        image: asbubam/hello-node
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello-node
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service-name: hello-node
