apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: /
    <source>
        @type forward
    </source>
    <match **>
        @type elasticsearch
        logstash_format true
        host localhost
        port 9200
        index_name test
        type_name fluentd
        flush_interval 5s
        <store>
            @type file
            path /logs/data.*.log
            symlink_path /logs/data.log time_slice_format %Y%m%d
            time_slice_wait 10m
            time_format %Y%m%dT%H%M%S%z
            compress gzip
            utc
        </store>
    </match>
