apiVersion: v1
kind: Service
metadata:
  name: loopchaintest
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 9002
    targetPort: 9002
    name: radio-station
  - port: 9000
    targetPort: 9000
    name: peer0
  selector:
    app: loopchain
